#!/usr/bin/env python3
"""Scatter plot of Weyl (b, c) points generated by decomposing A matrices.

This script generates A matrices from Young diagrams on the fly,
computes the TwoQubitWeylDecomposition (a, b, c) coordinates, and renders a
scatter plot of (b, c).
"""

import argparse

import matplotlib.pyplot as plt
import numpy as np
from qiskit.synthesis import TwoQubitWeylDecomposition
from yungdiagram import YoungDiagram

from compute_matrix import A_matrix
from helper import find_yds_with_fixed_addable_cells


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--max-diagram-size",
        type=int,
        required=True,
        help="Upper bound on Young diagram sizes to enumerate.",
    )
    return parser.parse_args()


def load_rows(max_diagram_size: int) -> dict[str, list[dict[str, float]]]:
    grouped: dict[str, list[dict[str, float]]] = {}

    diagrams = find_yds_with_fixed_addable_cells(4, max_diagram_size)

    for idx, diagram in enumerate(diagrams):
        label = str(diagram.partition)
        metrics = _diagram_metrics(diagram)

        matrix = A_matrix(diagram)
        decomp = TwoQubitWeylDecomposition(matrix)
        point = {
            "a": float(decomp.a),
            "b": float(decomp.b),
            "c": float(decomp.c),
            "entry": idx,
            **metrics,
        }
        grouped.setdefault(label, []).append(point)

    return grouped


def _diagram_metrics(diagram: YoungDiagram) -> dict[str, float]:
    dist = _partition_distance(diagram.partition, (3, 2, 1))
    return {
        "size": diagram.size,
        "distance": dist,
    }


def _partition_distance(parts: tuple[int, ...], base: tuple[int, ...]) -> float:
    """assume base is contained in parts"""
    padded_base = list(base) + [0] * (len(parts) - len(base))
    size_a, size_b = sum(parts), sum(base)
    return float(sum(abs(a / size_a - b / size_b) for a, b in zip(parts, padded_base)))


def main() -> None:
    args = parse_args()
    data = load_rows(args.max_diagram_size)
    xs, ys = [], []
    labels = []
    colors = []
    for diag, points in data.items():
        for p in points:
            xs.append(p["b"])
            ys.append(abs(p["c"]))
            labels.append(diag)
            colors.append(p["distance"])

    fig, ax = plt.subplots()
    sc = ax.scatter(xs, ys, s=12, alpha=0.5, c=colors, cmap="viridis")
    cbar = fig.colorbar(sc, ax=ax)
    cbar.set_label("Distance from (3, 2, 1)")
    _add_weyl_bc_boundary(ax)
    _add_hover_labels(fig, ax, sc, labels)
    ax.set_xlabel("b")
    ax.set_ylabel("|c|")
    ax.set_title("Weyl (b, c) scatter (a=pi/4)")
    ax.grid(True, alpha=0.3)
    fig.savefig("weyl-b-c-scatter.png", dpi=200, bbox_inches="tight")
    plt.show()


def _add_weyl_bc_boundary(ax) -> None:
    pi4 = np.pi / 4
    ax.plot([0, pi4], [0, 0], color="black", linewidth=1)
    ax.plot([0, pi4], [0, pi4], color="black", linewidth=1)
    ax.plot([pi4, pi4], [0, pi4], color="black", linewidth=1)


def _add_hover_labels(fig, ax, sc, labels: list[str]) -> None:
    annot = ax.annotate(
        "",
        xy=(0, 0),
        xytext=(6, 6),
        textcoords="offset points",
        bbox=dict(boxstyle="round", fc="w", alpha=0.8),
        arrowprops=dict(arrowstyle="->"),
    )
    annot.set_visible(False)

    def on_move(event) -> None:
        if event.inaxes != ax:
            if annot.get_visible():
                annot.set_visible(False)
                fig.canvas.draw_idle()
            return
        cont, ind = sc.contains(event)
        if cont and len(ind.get("ind", [])) > 0:
            i = ind["ind"][0]
            pos = sc.get_offsets()[i]
            annot.xy = pos
            annot.set_text(labels[i])
            annot.set_visible(True)
            fig.canvas.draw_idle()
        elif annot.get_visible():
            annot.set_visible(False)
            fig.canvas.draw_idle()

    fig.canvas.mpl_connect("motion_notify_event", on_move)


if __name__ == "__main__":
    main()
